//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewspaperDoAnV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Likeds = new HashSet<Liked>();
            this.Newspapers = new HashSet<Newspaper>();
        }
    
        public int UserID { get; set; }
        [Required(ErrorMessage = "Không Được Để Trống")]
        public string UserName { get; set; }

        [DataType(DataType.EmailAddress , ErrorMessage = "Sai Định Dạng")]
        public string UserEmail { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Không Được Để Trống")]
        public string UserPassword { get; set; }

        [DataType(DataType.Password)]
        [Compare("UserPassword", ErrorMessage = "Mật Khẩu Không Trùng")]

        public string Repassword { get; set; }
        public int Role_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liked> Likeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newspaper> Newspapers { get; set; }
        public virtual Phan_Quyen Phan_Quyen { get; set; }
    }
}
